# Generated by Django 3.2.3 on 2021-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='namee',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
